import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-store-monthly-summary',
  templateUrl: './store-monthly-summary.component.html',
  styleUrls: ['./store-monthly-summary.component.scss']
})
export class StoreMonthlySummaryComponent implements OnInit {

  profitPace = [
    {
      id: 1,
      category: '',
      units: '',
      potential: ''
    }
  ]
  profitPaces: any[] = [
    {
      id: 1,
      category: 'All',
      isAnchor: true,
      isHeader: false,
      isToggler: true,
      unit: 0,
      potential: 3,
      orders: [
        {
          category: 1,
          unit: '123',
          potential: '123',
        },
      ],
    },
    {
      id: 2,
      category: 'Age (0-30)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 0,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (31-60)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (61-90)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (91-120)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (121-150)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (151-180)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (181-210)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (211-240)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (241-270)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (271-300)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (301-330)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (331-365)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'Age (366+)',
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      unit: 7,
      potential: 3,
      orders: [
        {
          id: 1,
          customer: '123',
        },
      ],
    }
  ];
  varSummary: any[] = [
    {
      id: 1,
      category: 'New Retail',
      notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      isYellow: false,
      isOrange: false,
      isPurple: false,
      isTotal: false,
      orders: [
        {
          category: 1,
          unit: '123',
          potential: '123',
        },
      ],
    },
    {
      id: 2,
      category: 'New Non Retail',
      notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      isYellow: false,
      isOrange: false,
      isPurple: false,
      isTotal: false,
      orders: [
        {
          category: 1,
          unit: '123',
          potential: '123',
        },
      ],
    },
    {
      id: 3,
      category: 'New Total',
      notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
      isAnchor: true,
      isHeader: true,
      isToggler: false,
      orders: [
        {
          category: 1,
          unit: '123',
          potential: '123',
        },
      ],
    },
    {
      id: 4,
      category: 'Pre-Owned Retail',
      notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
      isAnchor: true,
      isHeader: false,
      isToggler: true,
      preOwned: [
        {
          category: 'Certified Retail',
          notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
        },
        {
          category: 'Non-Certified Retail',
          notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
        },
        {
          category: 'Other Makes Retail',
          notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
        },
      ],
    },
    {
      id: 5,
      category: 'Pre-Owned Non Retail',
      notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
      isAnchor: true,
      isHeader: false,
      isToggler: true,
      preOwned: [
        {
          category: 'Certified Non Retail',
          notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
        },
        {
          category: 'Non-Certified Non Retail',
          notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
        },
        {
          category: 'Other Makes Non Retail',
          notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
        },
      ],
    },
    {
      id: 6,
      category: 'Pre-Owned Total',
      notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      isYellow: false,
      isOrange: false,
      isPurple: true,
      isTotal: false,
      orders: [
        {
          category: 1,
          unit: '123',
          potential: '123',
        },
      ],
    },
    {
      id: 7,
      category: 'Total Retail',
      notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      isYellow: false,
      isOrange: true,
      isPurple: false,
      isTotal: false,
      orders: [
        {
          category: 1,
          unit: '123',
          potential: '123',
        },
      ],
    },
    {
      id: 8,
      category: 'Total Non Retail',
      notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      isYellow: true,
      isOrange: false,
      isPurple: false,
      isTotal: false,
      orders: [
        {
          category: 1,
          unit: '123',
          potential: '123',
        },
      ],
    },
    {
      id: 9,
      category: 'Total',
      notFinal: 0,
      final: 3,
      mtd: 3,
      tracking: 3,
      forecast: 3,
      var: 3,
      lastYear: 3,
      lastYearVar: 3,
      grossPack: 3,
      grossnotFinal: 0,
      grossfinal: 3,
      grossmtd: 3,
      grosstracking: 3,
      grossforecast: 3,
      grossvar: 3,
      grosslastYear: 3,
      grosslastYearVar: 3,
      pvMtd: 3,
      pvForecast: 3,
      pvLastYear: 3,
      isAnchor: true,
      isHeader: false,
      isToggler: false,
      isYellow: false,
      isOrange: false,
      isPurple: false,
      isTotal: true,
      orders: [
        {
          category: 1,
          unit: '123',
          potential: '123',
        },
      ],
    },
  ];
  constructor() { }

  ngOnInit(): void {
  }

}
